### ISSUE TITLE
怎么部署主平台？

### ISSUE THREAD

**Issue by smarttang** [smarttang/w3a_SOC#1]
1、首先下载项目
 git clone https://github.com/smarttang/w3a_SOC.git

2、放到自己的环境中,然后修改一个配置文件
 具体文件在：w3a_SOC / application / config / database.php

$db['default']['hostname'] = 'localhost';
$db['default']['username'] = 'root';
$db['default']['password'] = '123456';
$db['default']['database'] = 'w3a_system';
$db['default']['dbdriver'] = 'mysql'; 修改帐号密码以及创建同名的库。 

3、导入数据库 文件地址：w3a_SOC / db_sql/ w3a_system_new.sql

**Comment by delgyd** [comment]
然后呢？
登陆页面，点忘记密码无反应，，点注册报404

**Comment by smarttang** [comment]
你有邮箱么？能邮件交流么？

在 2014-09-03 11:12:18，"delgyd" notifications@github.com 写道：

然后呢？
登陆页面，点忘记密码无反应，，点注册报404

**Comment by delgyd** [comment]
太好了。。以下是我邮箱，请多多指教
guoqing.hu@starcor.cn

**Comment by delgyd** [comment]
!!!!

发件人： Tangyucong
发送时间： 2014-09-03 23:18
收件人： smarttang/w3a_SOC
抄送： delgyd
主题： Re: [w3a_SOC] 怎么部署主平台？ (#1)
你有邮箱么？能邮件交流么？

在 2014-09-03 11:12:18，"delgyd" notifications@github.com 写道：

然后呢？
登陆页面，点忘记密码无反应，，点注册报404

**Comment by smarttang** [comment]
。。。。你把邮箱给我，我跟你交流下把。。我这部署是么有问题的。。。                             原始邮件                             发件人: delgydnotifications@github.com收件人: smarttang/w3a_SOCw3a_SOC@noreply.github.com抄送: Tangyucongtangyucong@163.com发送时间: 2014年9月3日(周三) 23:46主题: Re: [w3a_SOC] 怎么部署主平台？ (#1)!!!!

发件人： Tangyucong

发送时间： 2014-09-03 23:18

收件人： smarttang/w3a_SOC

抄送： delgyd

主题： Re: [w3a_SOC] 怎么部署主平台？ (#1)

你有邮箱么？能邮件交流么？

在 2014-09-03 11:12:18，"delgyd" notifications@github.com 写道：

然后呢？

登陆页面，点忘记密码无反应，，点注册报404

**Comment by sx4mk** [comment]
There is a problem.click the login prompt 400.my email address is 0101v@sina.com.please contact me.thinks.

**Comment by scottlibing** [comment]
请教下从https://github.com/smarttang/w3a_SOC 下载后的w3a_SOC-master.zip怎么部署和启动？

**Comment by scottlibing** [comment]
my mail is scott_libing@163.com，pls contact me.thinks

**Comment by ytc301** [comment]
是啊就看到登陆界面进不去，看数据库里面 user表里面的用户密码admin,admin登录还是有问题，是否nginx需要写rewrite ？
登录后的地址是这个不存在 http://192.168.0.79:8022/index.php/inc/check/login_in

**Comment by smarttang** [comment]
nginx 需要写rewrite.

在 2015-10-13 16:05:46，"ytc301" notifications@github.com 写道：

是啊就看到登陆界面进不去，看数据库里面 user表里面的用户密码admin,admin登录还是有问题，是否nginx需要写rewrite ？
登录后的地址是这个不存在 http://192.168.0.79:8022/index.php/inc/check/login_in

**Comment by ytc301** [comment]
能把nginx相关的配置文件贴下吗？或者传到你代码上加个说明

**Comment by smarttang** [comment]
目前可能没有配置那个。

在 2015-10-14 11:46:50，"ytc301" notifications@github.com 写道：

能把nginx相关的配置文件贴下吗？或者传到你代码上加个说明

**Comment by ytc301** [comment]
那你用什么跑的，apache吗？
你跑的那个把配置贴下看看

**Comment by LinJie-Guo** [comment]
nginx 上跑各种错吗？ 不如建个QQ群，大家一起交流吧

**Comment by LinJie-Guo** [comment]
知道什么原因了，<?= 短标签没有开启

**Comment by ytc301** [comment]
说说你怎么跑起来的?

**Comment by LinJie-Guo** [comment]
不行。还是有问题

**Comment by ADOOO** [comment]
要在php.ini文件中设置short_open_tag为on
然后就可以正常使用了

**Comment by gitfuzzing** [comment]
新版本还没更新？只是有图片？

**Comment by ytc301** [comment]
你们跑起来的吗？

**Comment by ytc301** [comment]
用apache 还是nginx跑的？贴个相关配置文件信息看下

**Comment by qiujianzhong** [comment]
vim xx.conf
#add
rewrite ^(.*)/w3a/([a-z0-9\_]+\.php) $1/w3a/index.php?$2 last;
or
rewrite ^(.*)/([a-z0-9\_]+\.php) $1/index.php?$2 last;


#reload nginx
/etc/init.d/nginx reload

**Comment by qiujianzhong** [comment]
部署和说明文档都不完善，用的太吃力(⊙﹏⊙)b

**Comment by SpZanG** [comment]
@qiujianzhong
你好，我尝试那两条rewrite rule， 但是还是显示404.
我不论是放到w3a还是根目录 都是404.

可能是哪里的问题呢？ 谢谢

**Comment by SpZanG** [comment]
你好，我在apache上搭建之后，登录就会提示 "没有数据，或数据异常，请检查数据。" 请问，应该在哪里设置数据？谢谢

**Comment by cnwpdb** [comment]
谁来建个微信群或者QQ群方便交流啊

**Comment by liangxuanhao** [comment]
部署完 使用admin登录报404的错误，可以贴一下你nginx的配置文件吗
