### ISSUE TITLE
网站监控问题

### ISSUE THREAD

**Issue by gitfuzzing** [smarttang/w3a_SOC#5]
下载安装部署成功后，网络监控的原理我看介绍是通过ping，但是添加了地址url貌似没有效果

**Comment by smarttang** [comment]
请部署agent，部署了agent才可以实现监控的效果。

**Comment by gitfuzzing** [comment]
可以不在同一网络中监控吗？   公网传输

**Comment by smarttang** [comment]
自己实验一下啊，看看代码啊。

发自我的 iPhone

**Comment by ADOOO** [comment]
agent如何部署呢？

**Comment by smarttang** [comment]
agent怎么部署请看看agent的脚本。
把它放到自己的服务器部署。
